config/routes.rb
Abridgr::Application.routes.draw do
  
  devise_for :users, :controllers => { :sessions => "sessions", :registrations => "registrations"}
  resources :posts

  root 'welcome#index'
  get 'welcome/topics'

  get 'topic/:topic', to: 'topics#index', as: :topic
  resources :posts
  resources :topics

  get 'newtopic', to: 'topics#new'

  get "connect", to: 'welcome#connect'
  post '/news_user/create' => 'news_user#create'
  

end

app/models/news_user.rb
class NewsUser < ActiveRecord::Base
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :taggings
  has_many :topics, through: :taggings

  def slug
    title.downcase.gsub(" ", "-")
  end


  def to_param
    "#{id}-#{slug}"
  end



  def self.tagged_with(name)
    Topic.find_by_name!(name).posts
  end

  
  def tag_list
    self.topics.map(&:name).join(", ")
  end
  
  def tag_list=(names)
    self.topics = names.split(",").map do |n|
      Topic.where(name: n.strip).first_or_create!
    end
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :topic
  belongs_to :post
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  
  has_many :taggings
  has_many :posts, through: :taggings
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :newsletter

  def newsletter
    @news_user = NewsUser.new
  end
end

app/controllers/news_user_controller.rb
class NewsUserController < ApplicationController
  
  def new
  	@news_user = NewsUser.new
  end
  def create
    @user = NewsUser.new(news_user_params)
 
    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        NewsMailer.welcome_email(@user).deliver
 
        format.html { redirect_to(root_path, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def news_user_params
      params.require(:news_user).permit(:email)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    # @posts = Post.paginte(page: params[:page], per_page: 4).order('created_at DESC')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    render layout: false
  end

  # GET /posts/new
  def new
    if current_user.admin?
      @post = Post.new
    else
      redirect_to root_path
    end
  end

  # GET /posts/1/edit
  def edit
    unless current_user.admin?
      redirect_to root_path
    end


  end

  # POST /posts
  # POST /posts.json
  def create
    if current_user.admin?
      @post = Post.new(post_params)

      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render action: 'show', status: :created, location: @post }
        else
          format.html { render action: 'new' }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :author, :source, :site_url, :tag_list, :headline)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    layout false  
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
    layout false
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

	def index
		@posts = Post.tagged_with(params[:topic]).paginate(page: params[:page], per_page: 7).order('created_at DESC')
		@topic = Post.tagged_with(params[:topic]).first
    @topics = Topic.all.distinct.order('created_at DESC').first(5)
	end


	def new
    if current_user.admin?
		  @topic = Topic.new
    else 
      redirect_to root_path
    end	
  end

	def create
    if current_user.admin?
      @topic = Topic.new(topic_params)

      respond_to do |format|
        if @topic.save
          format.html { redirect_to "/", notice: 'Post was successfully created.' }
          format.json { render action: 'show', status: :created, location: @post }
        else
          format.html { render action: 'new' }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path
    end
  end
private
	def topic_params
      params.require(:topic).permit(:name, :picture_url, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	# @topics = Topic.paginate(page: params[:page], per_page: 5).order('created_at DESC')
    @topics = Topic.all.order('created_at DESC').first(5)

    @posts = Post.where(headline: true).paginate(page: params[:page], per_page: 7).order('created_at DESC')
  	respond_to do |format|
  		format.html
  		format.js
	   end
  	
  end

  def topics 
    @topics = Topic.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end

  def connect
    render layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_user_helper.rb
module NewsUserHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Abridgr | What You Need to Know. Simply</title>
    
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link href='http://fonts.googleapis.com/css?family=Raleway:800,200' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

      
</head>
<body>
      <div id="menu">
            <ul>
                <li><i class="fa fa-home"></i><%= link_to "Home", root_path %></li>
                <li><i class="fa fa-comments-o"></i><%= link_to "Connect", connect_path %></li>                
            </ul>
        </div>

            <div class="sidebar col-md-5 col-sm-12 ">

                <span class="menu-trigger side-writer-icon animated fadeInDown">
                    <span class="bar"></span>
                    <span class="bar"></span>
                    <span class="bar"></span>
                </span>

                <!-- if the user has javascript disabled they can still use the menu -->
                <noscript>
                    <div class="no-js-menu">
                        <ul>
                            <li><i class="entypo-home"></i><%= link_to "Home", root_path %></li>
                           <li><i class="entypo-user"></i><%= link_to "Connect", connect_path %></li>
                        </ul>
                    </div>
                </noscript>
                <!-- end no script -->

                <div class="site-info">
                    <div class="primary-info">
                    <h1>Abridgr</h1>
                        <p>All News, All Viewpoints, Abrigd </p>

                        
                    
                    <div class="secondary-info">

                        <%= form_for @news_user, url: {controller: "news_user", action: "create"} do |f| %>
                            <%= f.label :email, "Personalize Your Feed Waiting List" %><br>
                            <%= f.email_field :email, :placeholder => "Email (eg. ElonMusk@aol.com)", :class => "form-control" %>

                        <% end %>
                    </div>
                    </div>
                </div>

            </div>

<%= yield %>

  
    <script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-52635767-1', 'auto');
	  ga('send', 'pageview');

	</script>
  
  
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :site_url %><br>
    <%= f.text_field :site_url %>
  </div>
  <div class="field">
    <%= f.label :tag_list, "Topic" %><br>
    <%= f.text_field :tag_list %>
  </div>
  <div>
    <%= f.label :headline %>
    <%= f.check_box :headline %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/posts/_post.html.erb
                <div class="post">
                    <section>
                        <div class="post-preview col-xs-10  no-gutter" >

                              <h2><%= link_to "#{post.title}", post_path(post) %></h2>
                                    <p><%= post.body %> </p>
                              <p class="meta">
                                 <%= post.author %> in <%= link_to "#{post.source}", "#{post.site_url}", :target => "_blank" %> <i class="link-spacer"></i> <i class="fa fa-slack" style="color: black;"></i> <%= link_to "#{post.tag_list}", topic_path("#{post.tag_list}"), :class => "topic-font", :style => "color: black;" %>
                                 <a class="fa fa-twitter pull-right twitter-share-butto" target="_blank"   href=<%= "http://twitter.com/intent/tweet?text=" +  URI.encode(post.title) + "&url=http://abridgr.com" + URI.encode(post_path(post)) + "&via=abrdgr"  %> ></a><a class="fa fa-facebook pull-right" target="_blank" href=<%= "https://www.facebook.com/dialog/feed?app_id=1475336216022247&display=popup&caption=" + URI.encode(post.body) + "&link=http://abridgr.com" + URI.encode(post_path(post)) + "&redirect_uri=https://abridgr.com" %>></a>
                              </p>
                        </div>
                        

                    </section>
                </div>

        
            
            

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/new.html.erb
<div class="col-xs-offset-7">
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
                
<head>
  <title>Abridgr | What You Need to Know. Simply</title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

      
</head>
<span class="menu-trigger writer-icon animated fadeInDown">
        <span class="bar"></span>
        <span class="bar"></span>
        <span class="bar"></span>
    </span>
    

        <!-- if the user has javascript disabled they can still use the menu -->
        <noscript>
            <div class="no-js-menu">
                <ul>
                    <li><i class="fa fa-home"></i><%= link_to "Home", root_path %></li>
                    <li><i class="fa fa-comments-o"></i><%= link_to "Connect", connect_path %></li>
                </ul>
            </div>
        </noscript>
        <!-- end no script -->

    

    <div class="container">
        <div class="row">

          <div id="menu">
              <ul>
                  <li><i class="fa fa-home"></i><%= link_to "Home", root_path %></li>
                <li><i class="fa fa-comments-o"></i><%= link_to "Connect", connect_path %></li>

              </ul>
          </div>
          <div class="col-xs-12 main-content single-content">
            <p class="meta meta-show">
                <%= @post.author %> in <%= link_to "#{@post.source}", "#{@post.site_url}" %></a> <i class="link-spacer"></i> <i class="fa fa-slack"></i> <%= link_to "#{@post.tag_list}", topic_path(@post.tag_list), :class => "topic-font" %>
            </p>
            <h1><%= @post.title %></h1>

            <!-- <p class="subtitle">Like I said, never told...</p> -->


            <p style="font-family: 'Lato', sans-serif;"><%= @post.body %></p>

        <div class="single-footer">
            <div class="social clearfix">
                <!-- <a class="btn btn-writer btn-like" href="#"><i class="entypo-heart"></i>Like</a> -->
                

                
                    <a class="fa fa-twitter social-icon" target="_blank"  href=<%= "http://twitter.com/intent/tweet?text=" +  URI.encode(@post.title) + "&url=http://abridgr.com" + URI.encode(post_path(@post)) + "&via=abrdgr"  %> ></a></a>
                
                
                    <a class="fa fa-facebook-square social-icon" target="_blank" href=<%= "https://www.facebook.com/dialog/feed?app_id=1475336216022247&display=popup&caption=" + URI.encode(@post.body) + "&link=http://abridgr.com" + URI.encode(post_path(@post)) + "&redirect_uri=https://abridgr.com" %>></a>
                
               

            </div>
            <div class="category-list">
                <!--  -->
            </div>
        </div>

        </div><!-- main-content/col -->

        </div>
    </div>

app/views/topics/_topic.html.erb
<ul class="event-list">
<li>
							
							<img alt="Independence Day" src="<%= topic.picture_url %>" />
							<div class="info">
								<h2 class="title"><%= link_to "#{topic.name}", topic_path(topic.name) %></h2>
								<p class="desc"><%= topic.description %></p>
							</div>
							<div class="social">
								<ul>
									<li class="facebook" style="width:33%;"><a target="_blank" href=<%= "https://www.facebook.com/dialog/feed?app_id=1475336216022247&display=popup&caption=" + URI.encode("An Abridged Look At All The ") + URI.encode(topic.name) + URI.encode(" News") + "&link=http://abridgr.com" + URI.encode(topic_path(topic)) + "&redirect_uri=https://abridgr.com" %>><span class="fa fa-facebook"></span></a></li>
                                    <li class="twitter" style="width:34%;"><a target="_blank"   href=<%= "http://twitter.com/intent/tweet?text=" + URI.encode("An Abridged Look At All ") +  URI.encode(topic.name) + URI.encode(" Stories") + "&url=http://abridgr.com" + URI.encode(topic_path(topic)) + "&via=abrdgr"  %>><span class="fa fa-twitter"></span></a></li>
                                    <li class="google-plus" style="width:33%;"><a target="_blank" href=<%= "http://plus.google.com/share?url=http://abridgr.herokuapp.com" + URI.encode(topic_path(topic)) %>><span class="fa fa-google-plus"></span></a></li>
								</ul>
							</div>
						</li>
</ul>

app/views/topics/index.html.erb

            <div class="col-md-7 col-sm-12 col-md-offset-5 main-content">

                <div class="nav">
                	<i class="fa fa-slack"></i><%= link_to "#{@topic.tag_list}", "javascript:void(0);", :class => "select-posts active" %>
                    
                    <%= link_to "Topics", "javascript:void(0);", :class => "select-categories" %>
                </div>
            

            <div class="home-page-posts animated fadeIn " id="my-posts-topics">
                <%= render @posts %>
            </div>
            <div id="infinite-scrolling">
                <%= will_paginate @posts %>
            </div>
            <div class="home-page-categories hide animated fadeIn ">
            	<ul class="event-list">
            		<% @topics.each do |t| %>
                        <li>
                            
                            <img alt="Independence Day" src="<%= t.picture_url %>" />
                            <div class="info">
                                <h2 class="title"><%= link_to "#{t.name}", topic_path(t.name) %></h2>
                                <p class="desc"><%= t.description %></p>
                            </div>
                            <div class="social">
                                <ul>
                                    <li class="facebook" style="width:33%;"><a target="_blank" href=<%= "https://www.facebook.com/dialog/feed?app_id=1475336216022247&display=popup&caption=" + URI.encode("An Abridged Look At All The ") + URI.encode(t.name) + URI.encode(" News") + "&link=http://abridgr.com" + URI.encode(topic_path(t)) + "&redirect_uri=https://abridgr.com" %>><span class="fa fa-facebook"></span></a></li>
                                    <li class="twitter" style="width:34%;"><a target="_blank"   href=<%= "http://twitter.com/intent/tweet?text=" + URI.encode("An Abridged Look At All ") +  URI.encode(t.name) + URI.encode(" Stories") + "&url=http://abridgr.com" + URI.encode(topic_path(t)) + "&via=abrdgr"  %>><span class="fa fa-twitter"></span></a></li>
                                    <li class="google-plus" style="width:33%;"><a target="_blank" href=<%= "http://plus.google.com/share?url=http://abridgr.herokuapp.com" + URI.encode(topic_path(t)) %>><span class="fa fa-google-plus"></span></a></li>
                                </ul>
                                
                            </div>
                        </li>
                    <% end %>

					
				</ul>
                <%= link_to "Show More", welcome_topics_path %>
            </div>
		</div>

 		

app/views/topics/index.js.erb
$('#my-posts-topics').append('<%= j render @posts %>');
             <% if @posts.next_page %>
                  $('.pagination').replaceWith('<%= j will_paginate @posts %>');
             <% else %>
              $(window).off('scroll');
                 $('.pagination').remove();
             <% end %>

app/views/topics/new.html.erb
 <div class="col-xs-offset-7">
  <%= form_for(@topic) do |f| %>
    <% if @topic.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% @topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
   
    <div class="field">
      <%= f.label :picture_url %><br>
      <%= f.text_field :picture_url %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/welcome/connect.html.erb
                
<head>
  <title>Abridgr | What You Need to Know. Simply</title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

      
</head>
<div class="intro-background">
<span class="menu-trigger writer-icon animated fadeInDown">
        <span class="bar"></span>
        <span class="bar"></span>
        <span class="bar"></span>
    </span>
    

        <!-- if the user has javascript disabled they can still use the menu -->
        <noscript>
            <div class="no-js-menu">
                <ul>
                    <li><i class="fa fa-home"></i><%= link_to "Home", root_path %></li>
                    <li><i class="fa fa-comments-o"></i><%= link_to "Connect", connect_path %></li>
                </ul>
            </div>
        </noscript>
        <!-- end no script -->

    

    <div class="container">
        <div class="row">

          <div id="menu">
              <ul>
                  <li><i class="fa fa-home"></i><%= link_to "Home", root_path %></li>
                <li><i class="fa fa-comments-o"></i><%= link_to "Connect", connect_path %></li>

              </ul>
          </div>
        </div>
        <div class="trans-back">
          <h1>The Shortest Distance Between You and The News</h1>
          <p>Connect With Us Here:</p>
          <a class="fa fa-facebook" href="http://facebook.com/abridgr"></a><p>Facebook</p>
          <a class="fa fa-twitter" href="http://twitter.com/abrdgr"></a><p>Twitter</p>
        </div>
    </div>
</div>

app/views/welcome/index.html.erb
            
            <div class="col-md-7 col-sm-12 col-md-offset-5 main-content">

                <div class="nav">
                	<%= link_to "Latest", "javascript:void(0);", :class => "select-posts" %>
                    
                    <i class="fa fa-slack"></i><%= link_to "Topics", "javascript:void(0);", :class => "select-categories active" %>
                </div>
            

            <div class="home-page-posts hide animated fadeIn " id="my-posts">
            
                <%= render @posts %>
                
            </div>
            
             <div id="infinite-scrolling">
                   <%= will_paginate @posts %>
             </div>
             
            <div class="home-page-categories animated fadeIn " id="my-topics">
            	<ul class="event-list">

            		<%= render @topics %>

					
				</ul>
                <%= link_to "Show More", welcome_topics_path %>
            </div>
            


		</div>

  
 		

app/views/welcome/index.js.erb
$('#my-posts').append('<%= j render @posts %>');
             <% if @posts.next_page %>
                  $('.pagination').replaceWith('<%= j will_paginate @posts %>');
             <% else %>
              $(window).off('scroll');
                 $('.pagination').remove();
             <% end %>

app/views/welcome/topics.html.erb
<!DOCTYPE html>
    <div class="col-md-7 col-sm-12 col-md-offset-5 main-content">

                <div class="nav">
                    
                    
                    <i class="fa fa-slack"></i><%= link_to "Topics", "javascript:void(0);", :class => "select-categories" %>
                </div>
            

                        
            <div class="home-page-posts animated fadeIn " id="my-topics">
                <ul class="event-list">

                    <%= render @topics %>

                    
                </ul>
            </div>
            <div id="infinite-scrolling" class="event-list">
                
                   <%= will_paginate @topics %>

             </div>


        </div>

  
        

app/views/welcome/topics.js.erb
$('#my-topics').append('<%= j render @topics %>');
             <% if @topics.next_page %>
                  $('.pagination').replaceWith('<%= j will_paginate @topics %>');
             <% else %>
              $(window).off('scroll');
                 $('.pagination').remove();
             <% end %>